services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=sentinel_ugv
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME:-myuser}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-secret}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

